#
#     Author @Weesli
#


options:
  prefix: "&6RFriend &8>> "
  friend-limit: 10
  status:
    online: "&aOnline"
    offline: "&cOffline"
  settings-status:
    enabled: "&aEnabled"
    disabled: "&cDisabled"